#!/bin/bash

# This i3blocks blocklet checks which of two keyboard layouts ('no' and 'us' here) is in use and prints it on the bar
# Left-clicking the printed text switches between the two

if setxkbmap -query | grep 'us' > /dev/null; then
    case $BLOCK_BUTTON in
        1) setxkbmap -layout no ;; # left click
    esac
    printf 'English\n'
else
    case $BLOCK_BUTTON in
        1) setxkbmap -layout us ;; # left click
    esac
    printf 'Norsk\n'
fi
